### ISSUE TITLE
docker-nextcloud-dev_web_1 exited with code 1

### ISSUE THREAD

**Issue by RyanFletcher86** [skjnldsv/docker-nextcloud-dev#1]
Hello,

When kicking up the command docker-composer up, I'm getting the following error:

`docker-nextcloud-dev_web_1 exited with code 1`

Screenshot of my terminal here:

![image](https://user-images.githubusercontent.com/3360697/50285101-26a49000-0429-11e9-92b8-afdb4f3ac737.png)

Any suggestions on how to move forward?

**Comment by juliushaertl** [comment]
Quick fix: https://gist.github.com/juliushaertl/56326620587af574aa23db72e53e8e1c

@skjnldsv I guess we should allow to run this without ssl / with a pregenerated cert so that getting started is a bit easier.

**Comment by skjnldsv** [comment]
@juliushaertl this is in my plans yes :)

**Comment by RyanFletcher86** [comment]
@juliushaertl I applied the quick fix, this gets the nginx web server up and running. However when I browse to https://localhost:4443/ it returns "File not found".

![image](https://user-images.githubusercontent.com/3360697/50292152-6629a700-043e-11e9-848e-8de45309f65c.png)

This is what my folder directory currently looks like:

`

    Directory: E:\projects\docker-nextcloud-dev


Mode                LastWriteTime         Length Name                                                                                 
----                -------------         ------ ----                                                                                 
d-----       12/20/2018   9:57 AM                .github                                                                              
d-----       12/20/2018   9:57 AM                .idea                                                                                
d-----       12/20/2018   9:57 AM                .tx                                                                                  
d-----       12/20/2018   5:37 AM                3rdparty                                                                             
d-----       12/20/2018   9:57 AM                apps                                                                                 
d-----       12/20/2018   9:57 AM                build                                                                                
d-----       12/20/2018   9:57 AM                config                                                                               
d-----       12/20/2018   9:57 AM                contribute                                                                           
d-----       12/20/2018   9:57 AM                core                                                                                 
d-----       12/20/2018   9:52 AM                data                                                                                 
d-----       12/20/2018   9:58 AM                lib                                                                                  
d-----       12/20/2018   9:58 AM                ocm-provider                                                                         
d-----       12/20/2018   9:58 AM                ocs                                                                                  
d-----       12/20/2018   9:58 AM                ocs-provider                                                                         
d-----       12/20/2018   9:58 AM                resources                                                                            
d-----       12/20/2018   9:52 AM                server                                                                               
d-----       12/20/2018   9:58 AM                settings                                                                             
d-----       12/20/2018   9:58 AM                ssl                                                                                  
d-----       12/20/2018   9:58 AM                tests                                                                                
d-----       12/20/2018   9:58 AM                themes                                                                               
-a----       12/20/2018   5:37 AM             32 .bowerrc                                                                             
-a----       12/20/2018   5:37 AM            200 .codecov.yml                                                                         
-a----       12/20/2018   5:37 AM          43788 .drone.yml                                                                           
-a----       12/20/2018   5:37 AM           2251 .gitignore                                                                           
-a----       12/20/2018   5:37 AM             89 .gitmodules                                                                          
-a----       12/20/2018   5:37 AM           2836 .htaccess                                                                            
-a----       12/20/2018   5:37 AM            586 .jshintrc                                                                            
-a----       12/20/2018   5:37 AM          20035 .mailmap                                                                             
-a----       12/20/2018   5:37 AM            834 .scrutinizer.yml                                                                     
-a----       12/20/2018   5:37 AM             12 .tag                                                                                 
-a----       12/20/2018   5:37 AM            163 .user.ini                                                                            
-a----       12/20/2018   5:37 AM          12063 AUTHORS                                                                              
-a----       12/20/2018   5:37 AM           1191 autotest-checkers.sh                                                                 
-a----       12/20/2018   5:37 AM           8343 autotest-external.sh                                                                 
-a----       12/20/2018   5:37 AM            851 autotest-js.sh                                                                       
-a----       12/20/2018   5:37 AM          13836 autotest.sh                                                                          
-a----       12/20/2018   5:37 AM            868 bower.json                                                                           
-a----       12/20/2018   5:37 AM            111 CHANGELOG.md                                                                         
-a----       12/20/2018   5:37 AM            938 CODE_OF_CONDUCT.md                                                                   
-a----       12/20/2018   5:37 AM            442 composer.json                                                                        
-a----       12/20/2018   5:37 AM           3650 console.php                                                                          
-a----       12/20/2018   5:37 AM          34520 COPYING                                                                              
-a----       12/20/2018   5:37 AM            558 COPYING-README                                                                       
-a----       12/20/2018   5:37 AM           4979 cron.php                                                                             
-a----       12/20/2018   8:35 AM           2101 docker-compose.yml                                                                   
-a----       12/20/2018   8:35 AM           3733 Dockerfile                                                                           
-a----       12/20/2018   5:37 AM            156 index.html                                                                           
-a----       12/20/2018   5:37 AM           3172 index.php                                                                            
-a----       12/20/2018   8:35 AM          35184 LICENSE                                                                              
-a----       12/20/2018   9:56 AM           5636 nextcloud.conf                                                                       
-a----       12/20/2018   5:37 AM            283 occ                                                                                  
-a----       12/20/2018  10:05 AM              0 output.txt                                                                           
-a----       12/20/2018   5:37 AM           2969 public.php                                                                           
-a----       12/20/2018   8:35 AM           2800 README.md                                                                            
-a----       12/20/2018   5:37 AM           5139 remote.php                                                                           
-a----       12/20/2018   5:37 AM             26 robots.txt                                                                           
-a----       12/20/2018   5:37 AM           2232 status.php                                                                           
-a----       12/20/2018   5:37 AM           1646 version.php                                                                          


`

**Comment by skjnldsv** [comment]
@RyanFletcher86 you need to clone the server repository inside the folder, not in the folder.
So the only structure you should have is:
- config
- server
- ssl
- docker-compose.yml
- nextcloud.conf

**Comment by RyanFletcher86** [comment]
@juliushaertl @skjnldsv Excellent, thank you for the clarifications. Still fairly new to this docker stuff, had a colleague introduce me to it. It's like discovering virtual machines for the first time, absolutely magical stuff!

**Comment by skjnldsv** [comment]
@RyanFletcher86 Yes it is :)
Since you're the first one ending on this repository (freshly created) please gives feedback on what is clear and what isn't ;)

**Comment by RyanFletcher86** [comment]
I've got a busy day going today, trying to get this set up nice and have been back and forth a lot from my machine.

I absolutely will give some feedback and perhaps propose some changes on the README to help a new onboarding!

That being said, I just ran into this file permission issue:

![image](https://user-images.githubusercontent.com/3360697/50299472-a80f1900-044f-11e9-800a-17491cda5154.png)

I assume this is as simple as running something along the lines of 

`docker-compose exec php chmod 0770 /var/www/html/data` ?

Most of what I've been doing has been through RDP on my android phone.

**Comment by skjnldsv** [comment]
No, the data is mounted, so you need to change it locally, not on the docker image :)

**Comment by RyanFletcher86** [comment]
> No, the data is mounted, so you need to change it locally, not on the docker image :)

Huh, so this is where my windows server knowledge runs completely dry. How would I set the appropriate permissions on a windows file-system in power shell to reflect what we would have in Linux to make the error message disappear? 

Aside from simply upgrading from windows to linux / mac? 😝

**Comment by skjnldsv** [comment]
Argh, you're on windows! ^^
You can try your command then, no idea what will happen! We'll see I guess :stuck_out_tongue_closed_eyes:

**Comment by RyanFletcher86** [comment]
Workaround found by setting 

`'check_data_directory_permissions' => false,`

on /server/config.php :D
