### ISSUE TITLE
OCP\Files\NotFoundException

### ISSUE THREAD

**Issue by NilsGriebner** [skjnldsv/docker-nextcloud-dev#10]
Hi, 

setup worked for about one or two weeks without error. Now I get:

```
Technical details

    Remote Address: 172.20.0.1
    Request ID: oVRh00Uw2k1gyUepC6ZJ
    Type: OCP\Files\NotFoundException
    Code: 0
    Message:
    File: /var/www/nextcloud/lib/private/legacy/helper.php
    Line: 488


Trace

#0 /var/www/nextcloud/apps/files/lib/Controller/ViewController.php(130): OC_Helper::getStorageInfo('/', false)
#1 /var/www/nextcloud/apps/files/lib/Controller/ViewController.php(175): OCA\Files\Controller\ViewController->getStorageInfo()
#2 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(166): OCA\Files\Controller\ViewController->index('', '', NULL, false)
#3 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(99): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files\Controller\ViewController), 'index')
#4 /var/www/nextcloud/lib/private/AppFramework/App.php(126): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')
#5 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#6 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#7 /var/www/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#8 /var/www/nextcloud/lib/base.php(975): OC\Route\Router->match('/apps/files/')
#9 /var/www/nextcloud/index.php(42): OC::handleRequest()
#10 {main}
```
I didn't change anything on server side, just cloned as described in docs. Is this some weird
permission stuff?

**Comment by skjnldsv** [comment]
It doesn't sounds related to this repo :)
Did you do a git clean, or git stash something?
Can you check you have the proper folders for your current test user in the data/USER/files directory?

**Comment by skjnldsv** [comment]
Also, please make sure to update your docker-compose file and nextcloud.conf if you edited them or have old versions :)

**Comment by NilsGriebner** [comment]
Thanks for your reply :) 

Checked out your points today:
* No git operations like `clean` or `stash` done.
* My testuser's folder only contains a `cache` subfolder.
* Compose file and `nextcloud.conf` are up to date. I didn't touch them.

If this is not related to this repo. Where else can I ask for help (solutions form google and help forum didn't work)?

**Comment by skjnldsv** [comment]
create a `files` folder in your user data folder :)

**Comment by NilsGriebner** [comment]
That's it :) Thank you. But I don't understand why it was missing. The weeks before it worked.

**Comment by skjnldsv** [comment]
It used to happen to me some times. I could only link it to doing some git stuff to change branch or delete untracked files.
Though it's been a while it did not happened to me :)
