### ISSUE TITLE
broken link for mysql-proxy

### ISSUE THREAD

**Issue by makayabou** [skjnldsv/docker-nextcloud-dev#11]
Hello,
it seems that https://downloads.mysql.com/archives/get/file/$MYSQL_PROXY_TAR_NAME.tar.gz as used in docker-mysql-proxy/Dockerfile is broken.

Here's the correct address: 
 https://downloads.mysql.com/archives/get/p/21/file/$MYSQL_PROXY_TAR_NAME.tar.gz
thanks

**Comment by skjnldsv** [comment]
Fixed! Thanks :)
