### ISSUE TITLE
Unable to create admin account, SQL: All backends are down

### ISSUE THREAD

**Issue by onny** [skjnldsv/docker-nextcloud-dev#12]
Hey,
I get following error trying to run Docker container:
```
 Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1105] (proxy) all backends are down 
```

Best regards
Jonas

**Comment by skjnldsv** [comment]
Probably an issue with one of your docker container directly, not related to this setup :)
Check your docker-compose logs
