### ISSUE TITLE
Class 'OCA\Viewer\Event\LoadViewer' not found

### ISSUE THREAD

**Issue by r-oleary** [skjnldsv/docker-nextcloud-dev#14]
I've got the docker NC environment running, and I'm trying to get the photos app in dev mode so I can start playing with it. 

I checked out the photos repo to the apps2 folder, and ran all of the commands as specified in the photos README. I enabled the photos app in NC. 

I can access NC on localhost just fine, but when I navigate to Photos I get this error.

    Technical details

    Remote Address: 172.22.0.1
    Request ID: Z3Gf8YhJb8FW1paffbWB
    Type: Exception
    Code: 0
    Message: Class 'OCA\Viewer\Event\LoadViewer' not found
    File: /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php
    Line: 110

    Trace

    #0 /var/www/nextcloud/lib/private/AppFramework/App.php(152): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Photos\Controller\PageController), 'index')
    #1 /var/www/nextcloud/lib/private/Route/Router.php(308): OC\AppFramework\App::main('OCA\\Photos\\Cont...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    #2 /var/www/nextcloud/lib/base.php(1009): OC\Route\Router->match('/apps/photos/')
    #3 /var/www/nextcloud/index.php(37): OC::handleRequest()
    #4 {main}

I'm creating this issue in this repo because it seems like it's something to do with how the photos app is resolving dependencies within this dockerized environment. But I could be totally off and this issue should be elsewhere.

Any help is appreciated.

**Comment by skjnldsv** [comment]
You need to clone Viewer to your dev environment.
This is a hard dependency
