### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by NilsGriebner** [skjnldsv/docker-nextcloud-dev#9]
Thank you for sharing this great setup! Works like a charm :heart:

**Comment by skjnldsv** [comment]
Thanks a lot for your message! :D
Out of curiosity, why are you using this? Custom app development? Working on server? For your own setup? :)

**Comment by NilsGriebner** [comment]
I'm using it for custom app development :)

**Comment by skjnldsv** [comment]
Awesome! 
Enjoy!! :hugs: 
If you have any recommendations or need help, please shoot! :rocket:
